# This is a basic workflow to help you get started with Actions

name: Print-var

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  user_name: "Chaminda"
  demo_name: "Variable Demo"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      job_var1: "job variable value"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Using Workflow Variables
        run: echo Hello, $user_name!
          Welcome to $demo_name!!!
          here is job var1 $job_var1
          here is step var1 $step_var1
        env:
          step_var1: "Step Variable Value"
      - name: Set user_name Varaible
        run: echo "::set-env name=user_name::Chandrasekara"
      - name: Set new_var Varaible
        run: echo "::set-env name=new_var::newvarvalue"
      - name: Using Variables
        run: echo Hello, $user_name!
          Welcome to $demo_name!!!
          here is job var1 $job_var1
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Print all variables
        run: 
          echo $CI, $HOME, $GITHUB_WORKFLOW, $GITHUB_RUN_ID, $GITHUB_RUN_NUMBER
          echo $GITHUB_ACTION, $GITHUB_ACTIONS, $GITHUB_ACTOR, $GITHUB_REPOSITORY
      - name: repo and env secrets
        run:
          echo ${{ secrets.portfolio_secret1 }}
          echo ${{ secrets.portfolio_env_secret1 }}
